// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc7vykgIpjF_9LHyR-24FzV9NJe-KVcxA',
    appId: '1:508039188814:web:29dd60d76d71ab0b954e1f',
    messagingSenderId: '508039188814',
    projectId: 'ilera-a7681',
    authDomain: 'ilera-a7681.firebaseapp.com',
    storageBucket: 'ilera-a7681.firebasestorage.app',
    measurementId: 'G-B2SRSN2V20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyVfKT7xdnWSvXt0a7s1sZ0Wf2oqnAa18',
    appId: '1:508039188814:android:c98333091adf73a3954e1f',
    messagingSenderId: '508039188814',
    projectId: 'ilera-a7681',
    storageBucket: 'ilera-a7681.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU8C_aRkJwcB3fSFUZfqhWUfXZnUku7dE',
    appId: '1:508039188814:ios:507404f9ede6e14c954e1f',
    messagingSenderId: '508039188814',
    projectId: 'ilera-a7681',
    storageBucket: 'ilera-a7681.firebasestorage.app',
    iosBundleId: 'com.example.ileraapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU8C_aRkJwcB3fSFUZfqhWUfXZnUku7dE',
    appId: '1:508039188814:ios:507404f9ede6e14c954e1f',
    messagingSenderId: '508039188814',
    projectId: 'ilera-a7681',
    storageBucket: 'ilera-a7681.firebasestorage.app',
    iosBundleId: 'com.example.ileraapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc7vykgIpjF_9LHyR-24FzV9NJe-KVcxA',
    appId: '1:508039188814:web:ba2a767361dc0f5a954e1f',
    messagingSenderId: '508039188814',
    projectId: 'ilera-a7681',
    authDomain: 'ilera-a7681.firebaseapp.com',
    storageBucket: 'ilera-a7681.firebasestorage.app',
    measurementId: 'G-7NP58MQQFV',
  );
}
