name: ileraapp
description: "A health app connecting patients with medical professionals"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core + Auth + Firestore + Storage
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.14.2
  firebase_storage: ^11.7.4

  # UI and UX
  fluttertoast: ^8.2.4
  image_picker: ^1.1.0
  google_fonts: ^6.2.1

  # State Management
  provider: ^6.1.2

  # Utils
  intl: ^0.19.0

  # iOS-style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
